name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          poetry install

      # --- Static Analysis --- #

      - name: Run Ruff (Linting)
        run: |
          poetry run ruff check .

      - name: Run Black (Formatting Check)
        run: |
          poetry run black --check .

      - name: Run Pip-Audit (Security Check)
        run: |
          poetry run pip-audit

      # --- Run Unit tests and check coverage --- #

      - name: Run Unit Tests with Coverage
        run: |
          poetry run pytest --cov=ffreedom_expenses --cov-fail-under=90

      # --- Run Behave Tests --- #

      - name: Download Wait-for-it Script
        run: curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
        shell: bash

      - name: Start Flask App in Background
        run: |
          poetry run flask --app=ffreedom_expenses run --host=0.0.0.0 &
          chmod +x wait-for-it.sh
          ./wait-for-it.sh localhost:5000 --timeout=10

      - name: Run Behave Tests
        run: |
          poetry run behave -D base_url=http://localhost:5000

      # --- Clean Up --- #

      - name: Stop Flask App
        if: always()
        run: |
          pkill -f "python run.py" || true
